version: 2.1
aliases:
- &ssh-fingerprint
    fingerprints:
      - "ae:83:a5:6c:93:c9:16:57:ec:21:b9:6f:9c:5a:10:9c"
- &install-dependencies
  name: Install Node Dependencies
  command: npm install
- &test
  name: Test
  command: npm run test
- &build
  name: Build
  command: npm run build
- &save-dependency-cache
  paths:
  - node_modules
  key: node_modules-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
- &restore-dependency-cache
  name: Restore dependency cache
  keys:
  - node_modules-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
  - node_modules-{{ arch }}-
- &sonar-scanner
  name: Sonar scanner
  command: |
    sonar-scanner \
        -Dsonar.projectKey=entur_${CIRCLE_PROJECT_REPONAME} \
        -Dsonar.organization=${SONAR_ORG} \
        -Dsonar.projectName=${CIRCLE_PROJECT_REPONAME} \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.login=${ENTUR_SONAR_PASSWORD} \
        -Dsonar.sources=src \
        -Dsonar.tests=src \
        -Dsonar.test.inclusions=src/**/*.spec.ts,src/**/*.spec.tsx,src/**/*.test.ts,src/**/*.test.tsx \
        -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info \
        -Dsonar.testExecutionReportPaths=test-report.xml
- &sonar-scanner-pull-request
  name: Sonar scanner pull request
  command: |
    sonar-scanner \
        -Dsonar.projectKey=entur_${CIRCLE_PROJECT_REPONAME} \
        -Dsonar.organization=${SONAR_ORG} \
        -Dsonar.projectName=${CIRCLE_PROJECT_REPONAME} \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.login=${ENTUR_SONAR_PASSWORD} \
        -Dsonar.sources=src \
        -Dsonar.tests=src \
        -Dsonar.test.inclusions=src/**/*.spec.ts,src/**/*.spec.tsx,src/**/*.test.ts,src/**/*.test.tsx \
        -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info \
        -Dsonar.testExecutionReportPaths=test-report.xml \
        -Dsonar.pullrequest.key=${CIRCLE_PULL_REQUEST##*/} \
        -Dsonar.pullrequest.branch=$CIRCLE_BRANCH \
        -Dsonar.pullrequest.base=master

executors:
    circleci-toolbox:
      docker:
        - image: eu.gcr.io/entur-system-1287/circleci-toolbox-image-java11
          auth:
            username: _json_key
            password: $DOCKER_PASSWORD

jobs:
  test-build:
    docker:
      - image: cimg/node:16.14.2
    steps:
    - checkout
    - restore_cache: *restore-dependency-cache
    - run: *install-dependencies
    - run: *build
    - run: *test
    - run: *sonar-scanner-pull-request
    - store_test_results:
        path: junit.xml
  build:
    docker:
      - image: cimg/node:16.14.2
    steps:
    - checkout
    - restore_cache: *restore-dependency-cache
    - run: *install-dependencies
    - run: *build
    - run: *test
    - run: *sonar-scanner
    - store_test_results:
        path: junit.xml
workflows:
  install-test-build-deploy:
    jobs:
    - test-build:
        name: npm-test-build
        context: global
        filters:
          branches:
            ignore:
            - master
    - build:
        name: npm-build
        context: global
        filters:
          branches:
            only:
            - master
