version: 2.1

orbs:
  node: circleci/node@4.7

workflows:
  build-and-test:
    jobs:
      - node/test:
          version: '16.10'
          pkg-manager: npm
      - node/build:
          version: '16.10'
          pkg-manager: npm
